name: Build and Push Docker image

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./build
          tags: ghcr.io/thueske/mstudio-php-viewer:latest
          platforms: linux/amd64,linux/arm64,linux

      - name: Do not automatically disable workflow execution
        uses: gautamkrishnar/keepalive-workflow@v1
